# Project IA - 2024

This project consists of the following:
- 0. Data collection
- 1. Dataset analysis

## 0. Dataset

The dataset used in this project is in the following site [Drug Consumption Dataset](https://www.kaggle.com/datasets/mexwell/drug-consumption-classification).

The dataset contains 1886 instances and 32 attributes. 

The dataset is composed of 31 attributes, 12 of them are real and the rest are strings. The attributes are:

The dataset contains 31 attributes, which are as follows:

-   **Age**: This is the age of the participant.
-   **Gender**: This is the gender of the participant.
-   **Education**: This is the  level of education of the participant. 
-   **Country**: This is the country of current residence of the participant
-   **Ethnicity**: This is the ethnicity of the participant.
-   **Nscore**: Nscore is NEO-FFI-R Neuroticism. Neuroticism is one of the Big Five higher-order personality traits in the study of psychology. Individuals who score high on neuroticism are more likely than average to be moody and to experience such feelings as anxiety, worry, fear, anger, frustration, envy, jealousy, guilt, depressed mood, and loneliness. 
-   **EScore**: Escore (Real) is NEO-FFI-R Extraversion. Extraversion is one of the five personality traits of the Big Five personality theory. It indicates how outgoing and social a person is. A person who scores high in extraversion on a personality test is the life of the party. They enjoy being with people, participating in social gatherings, and are full of energy.
-   **Oscore**: Oscore (Real) is NEO-FFI-R Openness to experience. Openness is one of the five personality traits of the Big Five personality theory. It indicates how open-minded a person is. A person with a high level of openness to experience in a personality test enjoys trying new things. They are imaginative, curious, and open-minded. Individuals who are low in openness to experience would rather not try new things. They are close-minded, literal and enjoy having a routine.
-   **Ascore**: Ascore(Real) is NEO-FFI-R Agreeableness. Agreeableness is one of the five personality traits of the Big Five personality theory. A person with a high level of agreeableness in a personality test is usually warm, friendly, and tactful. They generally have an optimistic view of human nature and get along well with others.
-   **Cscore**: Cscore (Real) is NEO-FFI-R Conscientiousness. Conscientiousness is one of the five personality traits of the Big Five personality theory. A person scoring high in conscientiousness usually has a high level of self-discipline. These individuals prefer to follow a plan, rather than act spontaneously. Their methodic planning and perseverance usually makes them highly successful in their chosen occupation.
-   **Impulsive**: Impulsive (Real) is impulsiveness measured by BIS-11. In psychology, impulsivity (or impulsiveness) is a tendency to act on a whim, displaying behavior characterized by little or no forethought, reflection, or consideration of the consequences. If you describe someone as impulsive, you mean that they do things suddenly without thinking about them carefully first.
-   **Sensation**: SS(Real) is sensation seeing measured by ImpSS. Sensation is input about the physical world obtained by our sensory receptors, and perception is the process by which the brain selects, organizes, and interprets these sensations. In other words, senses are the physiological basis of perception.
-   **Alcohol**: This is the rate of consumption of alcohol by the participant.
-   **Amphet**: This is the rate of consumption of amphet by the participant.
-   **Amyl**: This is the rate of consumption of amyl by the participant.
-   **Benzos**: This is the rate of consumption of benzos by the participant.
-   **Caff**: This is the rate of consumption of caff by the participant.
-   **Cannabis**: This is the rate of consumption of cannabis by the participant.
-   **Choc**: This is the rate of consumption of choc by the participant.
-   **Coke**: This is the rate of consumption of coke by the participant.
-   **Crack**: This is the rate of consumption of crack by the participant.
-   **Ecstasy**: This is the rate of consumption of ecstasy by the participant.
-   **Heroin**: This is the rate of consumption of heroin by the participant.
-   **Ketamine**: This is the rate of consumption of ketamine by the participant.
-   **Legalh**: This is the rate of consumption of legalh by the participant.
-   **LSD**: This is the rate of consumption of lsd by the participant.
-   **Meth**: This is the rate of consumption of meth by the participant.
-   **Mushroom**: This is the rate of consumption of mushroom by the participant.
-   **Nicotine**: This is the rate of consumption of nicotine by the participant.
-   **Semer**: This is the rate of consumption of semer by the participant.
-   **VSA**: This is the rate of consumption of vsa by the participant.

## 1. Dataset analysis

### 1.1. Importing the libraries

In [2]:
import pandas
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import warnings

from IPython.display import Image
from subprocess import call

### 1.2. Importing the dataset

In [6]:
# Load the data
df = pandas.read_csv("dataset.csv")

# Drop uneeded columns
df.drop(['ID'], axis=1, inplace=True)

# Print the first 5 rows of the data
df.head()

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,...,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA
0,0.49788,0.48246,-0.05921,0.96082,0.12600,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,...,CL0,CL0,CL0,CL0,CL0,CL0,CL0,CL2,CL0,CL0
1,-0.07854,-0.48246,1.98437,0.96082,-0.31685,-0.67825,1.93886,1.43533,0.76096,-0.14277,...,CL4,CL0,CL2,CL0,CL2,CL3,CL0,CL4,CL0,CL0
2,0.49788,-0.48246,-0.05921,0.96082,-0.31685,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,...,CL0,CL0,CL0,CL0,CL0,CL0,CL1,CL0,CL0,CL0
3,-0.95197,0.48246,1.16365,0.96082,-0.31685,-0.14882,-0.80615,-0.01928,0.59042,0.58489,...,CL0,CL0,CL2,CL0,CL0,CL0,CL0,CL2,CL0,CL0
4,0.49788,0.48246,1.98437,0.96082,-0.31685,0.73545,-1.63340,-0.45174,-0.30172,1.30612,...,CL1,CL0,CL0,CL1,CL0,CL0,CL2,CL2,CL0,CL0

### 1.3 Data First Look

In [7]:
age = {
    -0.95197: '18-24',
    -0.07854: '25-34',
    0.49788: '35-44',
    1.09449: '45-54',
    1.82213: '55-64',
    2.59171: '65+'
}

gender = {
            0.48246: 'Female',
            -0.48246: 'Male'
}

country = {
            -0.09765: 'Australia',
            0.24923: 'Canada',
            -0.46841: 'New Zealand',
            -0.28519: 'Other',
            0.21128: 'Republic of Ireland',
            0.96082: 'UK',
            -0.57009: 'USA'
}

ethnicity = {
            -0.50212: 'Asian',
            -1.10702: 'Black',
            1.90725: 'Mixed-Black/Asian',
            0.12600: 'Mixed-White/Asian',
            -0.22166: 'Mixed-White/Black',
            0.11440: 'Other',
            -0.31685: 'White'
}

education = {
            -2.43591: 'Left School Before 16 years',
            -1.73790: 'Left School at 16 years',
            -1.43719: 'Left School at 17 years',
            -1.22751: 'Left School at 18 years',
            -0.61113: 'Some College,No Certificate Or Degree',
            -0.05921: 'Professional Certificate/ Diploma',
            0.45468: 'University Degree',
            1.16365: 'Masters Degree',
            1.98437: 'Doctorate Degree',
}

usage_col = {
    'CL0': 'Never Used',
    'CL1': 'Used over a Decade Ago',
    'CL2': 'Used in Last Decade',
    'CL3': 'Used in Last Year',
    'CL4': 'Used in Last Month',
    'CL5': 'Used in Last Week',
    'CL6': 'Used in Last Day',
}


            
df['Age'] = df['Age'].replace(age)
df['Gender'] = df['Gender'].replace(gender)
df['Country'] = df['Country'].replace(country)
df['Ethnicity'] = df['Ethnicity'].replace(ethnicity)
df['Education'] = df['Education'].replace(education)
df['Alcohol'] = df['Alcohol'].replace(usage_col)
df['Amphet'] = df['Amphet'].replace(usage_col)
df['Amyl'] = df['Amyl'].replace(usage_col)
df['Benzos'] = df['Benzos'].replace(usage_col)
df['Caff'] = df['Caff'].replace(usage_col)
df['Cannabis'] = df['Cannabis'].replace(usage_col)
df['Choc'] = df['Choc'].replace(usage_col)
df['Coke'] = df['Coke'].replace(usage_col)
df['Crack'] = df['Crack'].replace(usage_col)
df['Ecstasy'] = df['Ecstasy'].replace(usage_col)
df['Heroin'] = df['Heroin'].replace(usage_col)
df['Ketamine'] = df['Ketamine'].replace(usage_col)
df['Legalh'] = df['Legalh'].replace(usage_col)
df['LSD'] = df['LSD'].replace(usage_col)
df['Meth'] = df['Meth'].replace(usage_col)
df['Mushrooms'] = df['Mushrooms'].replace(usage_col)
df['Nicotine'] = df['Nicotine'].replace(usage_col)
df['Semer'] = df['Semer'].replace(usage_col)
df['VSA'] = df['VSA'].replace(usage_col)

#updated_dataset = "updated_dataset.csv"
#data.to_csv(updated_dataset, index=False)
df.head()

,Age,Gender,Education,Country,Ethnicity,Nscore,Escore,Oscore,Ascore,Cscore,...,Ecstasy,Heroin,Ketamine,Legalh,LSD,Meth,Mushrooms,Nicotine,Semer,VSA
0,35-44,Female,Professional Certificate/ Diploma,UK,Mixed-White/Asian,0.31287,-0.57545,-0.58331,-0.91699,-0.00665,...,Never Used,Never Used,Never Used,Never Used,Never Used,Never Used,Never Used,Used in Last Decade,Never Used,Never Used
1,25-34,Male,Doctorate Degree,UK,White,-0.67825,1.93886,1.43533,0.76096,-0.14277,...,Used in Last Month,Never Used,Used in Last Decade,Never Used,Used in Last Decade,Used in Last Year,Never Used,Used in Last Month,Never Used,Never Used
2,35-44,Male,Professional Certificate/ Diploma,UK,White,-0.46725,0.80523,-0.84732,-1.62090,-1.01450,...,Never Used,Never Used,Never Used,Never Used,Never Used,Never Used,Used over a Decade Ago,Never Used,Never Used,Never Used
3,18-24,Female,Masters Degree,UK,White,-0.14882,-0.80615,-0.01928,0.59042,0.58489,...,Never Used,Never Used,Used in Last Decade,Never Used,Never Used,Never Used,Never Used,Used in Last Decade,Never Used,Never Used
4,35-44,Female,Doctorate Degree,UK,White,0.73545,-1.63340,-0.45174,-0.30172,1.30612,...,Used over a Decade Ago,Never Used,Never Used,Used over a Decade Ago,Never Used,Never Used,Used in Last Decade,Used in Last Decade,Never Used,Never Used

Let's take a look at the data using some graph pies.

In [1]:
# Plotting

NameError: name 'plt' is not defined